### PR TITLE
Change path order in backend to fix invite and request endpoints

### LINKED ISSUE #229: Decline and cancel invitations and requests endpoints not working
## Description
When a user is invited to join a group, he can't decline this invitation.
When a user has requested to join a group, he can't cancel this request.
When a user is invited to join a group, the group can't cancel this invitation.
When a user has requested to join a group, the group can't decline this request.

## Endpoints
DELETE /api/groups/:groupID/members/invitation
DELETE /api/groups/:groupID/members/request

Moreover these endpoints are not documented.

### PR DESCRIPTION
**Pull request by TomRomeo**
## Description

This PR rearranges the paths in the backend api so the invite/request accept/decline endpoints are not overwritten.

## Resolved Issues
resolves #229

### CODE REVIEW

**Review by Julian702 — APPROVED** [review]

File: backend/services/frontend/main.go [hunk 1]
```diff
@@ -116,18 +116,18 @@ func main() {
...
 	app.Get("/api/groups/:groupID/members/requests", svc.GetGroupMemberRequestsHandler)
 	app.Get("/api/groups/:groupID/members/invitations", svc.GetInvitationsForGroupHandler)
-
 	app.Post("/api/groups/:groupID/members/invitation", svc.AddUserGroupInviteHandler)
 	app.Delete("/api/groups/:groupID/members/invitation", svc.RemoveUserGroupInviteHandler)
 	app.Post("/api/groups/:groupID/members/request", svc.AddUserGroupRequestHandler)
 	app.Delete("/api/groups/:groupID/members/request", svc.RemoveUserGroupRequestHandler)
 
+	app.Get("/api/groups/:groupID/members", svc.GetGroupMembersHandler)
+	app.Delete("/api/groups/:groupID/members", svc.LeaveGroupHandler)
```
Comment (4KevR) [inline backend/services/frontend/main.go:127]: I think I would place these two endpoints at their old position (to kind of "introduce" the /members subpath). Also I think it would be beneficial to also reorder the handlers in the `frontend.go` so that they still represent the order of the endpoints here to keep it organized.

**Review by 4KevR — CHANGES_REQUESTED** [review]
Great, I just have two small nits.

File: backend/api-documentation/groups/decline invitation.bru [hunk 2]
```diff
@@ -0,0 +1,15 @@
+meta {
+  name: decline invitation
```
[the remark this answers is not in the document]
Comment (Julian702) [reply backend/api-documentation/groups/decline invitation.bru:2]: No, the flip is on purpose. By sending a DELETE request to the /members/request endpoint, the invited user rejects this invitation. The other way around, the group rejects a request to join with a DELETE request to the /members/invitation endpoint.

File: backend/services/frontend/main.go (hunk 1 above)
Comment (TomRomeo) [reply backend/services/frontend/main.go]: I placed the two endpoints at the top again.
As the handlers are not ordered at the moment either, I would prefer to tackle the re-ordering in a separate refactoring PR.

**Review by memeToasty — APPROVED** [review]

File: backend/services/frontend/main.go (hunk 1 above)
Comment (4KevR) [reply backend/services/frontend/main.go]: Created issue #234

**Review by 4KevR — APPROVED** [review]
